### PR TITLE
Bring back compatibility with Java 8. Fixes #201.

### LINKED ISSUE #201: Java 8 support broken
After updating to the latest release (v1.2) we're now getting the following error when running our scans:
```
The plugin [aemrules] does not support Java 1.8.0_111: com/cognifide/aemrules/AemRulesSonarPlugin 
has been compiled by a more recent version of the Java Runtime (class file version 55.0), 
this version of the Java Runtime only recognizes class file versions up to 52.0
```
Was dropping Java 8 support intentional? If not, I think just setting the Maven compiler plugin's source/target settings to 1.8 would fix it.

### PR DESCRIPTION
**Pull request by raspy**
Plugin code executes within SonarScanner, which still supports Java 8. As the plugin cannot be deactivated per project, current requirement to use Java 11 renders any project that still uses Java 8 or Java 9 (think: Android projects) can no longer be analyzed on the SQ server that has aemrules installed.

It seems however that the main refactoring made when the plugin was migrated to Java 11 was to remove guava dependencies. Luckily enough all current code can be slightly modified to use pure Java 8 statements, hence dropping dependency on guava while remaining compatible with Java 8 (and SonarScanner).

Please consider including the changes in the official release and release through the marketplace.

### CODE REVIEW

**Comment by raspy** [comment]
@toniedzwiedz would you please help to review and include the changes in a release? It seems that there have been people impacted by #201 (including myself).

**Comment by toniedzwiedz** [comment]
Hi @raspy, thanks for the PR. I've had a cursory look at the code changes and they seem fine. Please also revert this commit https://github.com/Cognifide/AEM-Rules-for-SonarQube/commit/efc963d431ef1c870bdb9fc1c4600b236e085644 in your branch to ensure Travis also builds the project with JDK 8 (which should be possible if we use this source level).

**Comment by raspy** [comment]
Reverted as requested, seems to work with Travis as well.

**Review by toniedzwiedz — APPROVED** [review]

**Comment by toniedzwiedz** [comment]
@raspy it does, thanks. I'll kick off a release today.

**Pull request merged**
